//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileCabinetApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnglishSource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnglishSource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileCabinetApp.EnglishSource", typeof(EnglishSource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All records are exported to file {0}.
        /// </summary>
        internal static string All_records_are_exported_to_file {
            get {
                return ResourceManager.GetString("All_records_are_exported_to_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; .
        /// </summary>
        internal static string console {
            get {
                return ResourceManager.GetString("console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record #{0} is created.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date birth is null or whitespace.
        /// </summary>
        internal static string Date_birth_is_null_or_whitespace {
            get {
                return ResourceManager.GetString("Date_birth_is_null_or_whitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth: .
        /// </summary>
        internal static string date_of_birth {
            get {
                return ResourceManager.GetString("date_of_birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Cabinet Application, developed by {0}.
        /// </summary>
        internal static string developed_by {
            get {
                return ResourceManager.GetString("developed_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting an application....
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is exist - rewrite {0}? [Y/n].
        /// </summary>
        internal static string Export_File_is_exist {
            get {
                return ResourceManager.GetString("Export_File_is_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name: .
        /// </summary>
        internal static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your command, or enter &apos;help&apos; to get help..
        /// </summary>
        internal static string hint {
            get {
                return ResourceManager.GetString("hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered id is not an integer.
        /// </summary>
        internal static string id_is_not_an_integer {
            get {
                return ResourceManager.GetString("id_is_not_an_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job experience: .
        /// </summary>
        internal static string job_experience {
            get {
                return ResourceManager.GetString("job_experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name: .
        /// </summary>
        internal static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no &apos;{0}&apos; command..
        /// </summary>
        internal static string no_command {
            get {
                return ResourceManager.GetString("no_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}, {2}, {3:yyyy-MMM-dd}, {4}, {5}, {6}.
        /// </summary>
        internal static string print_record {
            get {
                return ResourceManager.GetString("print_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank: .
        /// </summary>
        internal static string rank {
            get {
                return ResourceManager.GetString("rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion failed: {0}. Please, correct your input..
        /// </summary>
        internal static string ReadInput_Conversion_failed {
            get {
                return ResourceManager.GetString("ReadInput_Conversion_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record {0} is removed.
        /// </summary>
        internal static string Record_is_removed {
            get {
                return ResourceManager.GetString("Record_is_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #{0} record is not found..
        /// </summary>
        internal static string record_not_found {
            get {
                return ResourceManager.GetString("record_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} records were written to {1}.
        /// </summary>
        internal static string records_were_written_to {
            get {
                return ResourceManager.GetString("records_were_written_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} record(s)..
        /// </summary>
        internal static string stat {
            get {
                return ResourceManager.GetString("stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record #{0} is updated.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed: {0}. Please, correct your input..
        /// </summary>
        internal static string Validation_failed {
            get {
                return ResourceManager.GetString("Validation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation rules = {0}.
        /// </summary>
        internal static string validation_rules {
            get {
                return ResourceManager.GetString("validation_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wage: .
        /// </summary>
        internal static string wage {
            get {
                return ResourceManager.GetString("wage", resourceCulture);
            }
        }
    }
}
