//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileCabinetApp {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnglishSource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnglishSource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FileCabinetApp.EnglishSource", typeof(EnglishSource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string developed_by {
            get {
                return ResourceManager.GetString("developed_by", resourceCulture);
            }
        }
        
        internal static string console {
            get {
                return ResourceManager.GetString("console", resourceCulture);
            }
        }
        
        internal static string no_command {
            get {
                return ResourceManager.GetString("no_command", resourceCulture);
            }
        }
        
        internal static string stat {
            get {
                return ResourceManager.GetString("stat", resourceCulture);
            }
        }
        
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        internal static string id_is_not_an_integer {
            get {
                return ResourceManager.GetString("id_is_not_an_integer", resourceCulture);
            }
        }
        
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        internal static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        internal static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        internal static string date_of_birth {
            get {
                return ResourceManager.GetString("date_of_birth", resourceCulture);
            }
        }
        
        internal static string job_experience {
            get {
                return ResourceManager.GetString("job_experience", resourceCulture);
            }
        }
        
        internal static string wage {
            get {
                return ResourceManager.GetString("wage", resourceCulture);
            }
        }
        
        internal static string rank {
            get {
                return ResourceManager.GetString("rank", resourceCulture);
            }
        }
        
        internal static string hint {
            get {
                return ResourceManager.GetString("hint", resourceCulture);
            }
        }
        
        internal static string ReadInput_Conversion_failed {
            get {
                return ResourceManager.GetString("ReadInput_Conversion_failed", resourceCulture);
            }
        }
        
        internal static string Export_File_is_exist {
            get {
                return ResourceManager.GetString("Export_File_is_exist", resourceCulture);
            }
        }
        
        internal static string All_records_are_exported_to_file {
            get {
                return ResourceManager.GetString("All_records_are_exported_to_file", resourceCulture);
            }
        }
        
        internal static string records_were_written_to {
            get {
                return ResourceManager.GetString("records_were_written_to", resourceCulture);
            }
        }
        
        internal static string method_execution_duration_ticks {
            get {
                return ResourceManager.GetString("method_execution_duration_ticks", resourceCulture);
            }
        }
        
        internal static string ImportCommandHandler_The_format_is_not_supported {
            get {
                return ResourceManager.GetString("ImportCommandHandler_The_format_is_not_supported", resourceCulture);
            }
        }
        
        internal static string FindBy_is_not_presented_in_current_database {
            get {
                return ResourceManager.GetString("FindBy_is_not_presented_in_current_database", resourceCulture);
            }
        }
        
        internal static string Records_are_deleted {
            get {
                return ResourceManager.GetString("Records_are_deleted", resourceCulture);
            }
        }
        
        internal static string Records_0_where_updated {
            get {
                return ResourceManager.GetString("Records_0_where_updated", resourceCulture);
            }
        }
        
        internal static string ErrorCommandHandler_Handle_Is_Not_A_Command {
            get {
                return ResourceManager.GetString("ErrorCommandHandler_Handle_Is_Not_A_Command", resourceCulture);
            }
        }
        
        internal static string The_most_similar_commands_are {
            get {
                return ResourceManager.GetString("The_most_similar_commands_are", resourceCulture);
            }
        }
        
        internal static string Cannot_resolve_with_input_logical_operand {
            get {
                return ResourceManager.GetString("Cannot_resolve_with_input_logical_operand", resourceCulture);
            }
        }
        
        internal static string File_is_not_exist {
            get {
                return ResourceManager.GetString("File_is_not_exist", resourceCulture);
            }
        }
        
        internal static string Export_format_cannot_be_null {
            get {
                return ResourceManager.GetString("Export_format_cannot_be_null", resourceCulture);
            }
        }
        
        internal static string Export_type_is_not_supported {
            get {
                return ResourceManager.GetString("Export_type_is_not_supported", resourceCulture);
            }
        }
        
        internal static string Answer_must_be_either_Y_or_n {
            get {
                return ResourceManager.GetString("Answer_must_be_either_Y_or_n", resourceCulture);
            }
        }
        
        internal static string Cant_deserialize {
            get {
                return ResourceManager.GetString("Cant_deserialize", resourceCulture);
            }
        }
        
        internal static string Record_at_line_Error {
            get {
                return ResourceManager.GetString("Record_at_line_Error", resourceCulture);
            }
        }
        
        internal static string Error__wrong_conversion {
            get {
                return ResourceManager.GetString("Error__wrong_conversion", resourceCulture);
            }
        }
        
        internal static string missing_one_parameter {
            get {
                return ResourceManager.GetString("missing_one_parameter", resourceCulture);
            }
        }
        
        internal static string Wrong_data_format {
            get {
                return ResourceManager.GetString("Wrong_data_format", resourceCulture);
            }
        }
        
        internal static string Record_number_error {
            get {
                return ResourceManager.GetString("Record_number_error", resourceCulture);
            }
        }
        
        internal static string Cannot_find_keyword {
            get {
                return ResourceManager.GetString("Cannot_find_keyword", resourceCulture);
            }
        }
        
        internal static string Number_of_keys_doesnt_correspond_to_number_of_values {
            get {
                return ResourceManager.GetString("Number_of_keys_doesnt_correspond_to_number_of_values", resourceCulture);
            }
        }
        
        internal static string Parameter_values_should_be_enclosed_in_brackets {
            get {
                return ResourceManager.GetString("Parameter_values_should_be_enclosed_in_brackets", resourceCulture);
            }
        }
        
        internal static string Record_with_id_is_already_exist {
            get {
                return ResourceManager.GetString("Record_with_id_is_already_exist", resourceCulture);
            }
        }
        
        internal static string Id_cannot_be_updated {
            get {
                return ResourceManager.GetString("Id_cannot_be_updated", resourceCulture);
            }
        }
    }
}
